export const audioClips = [
  {
    keyCode: 49,
    code: 'Digit1',
    keyTrigger: '1',
    id: 'MC',
    url: '/sounds/808MC1_Orig.wav',
  },
  {
    keyCode: 50,
    code: 'Digit2',
    keyTrigger: '2',
    id: 'HC',
    url: '/sounds/808HC1_Orig.wav',
  },
  {
    keyCode: 51,
    code: 'Digit3',
    keyTrigger: '3',
    id: 'CL',
    url: '/sounds/808CL_Orig.wav',
  },
  {
    keyCode: 52,
    code: 'Digit4',
    keyTrigger: '4',
    id: 'MA',
    url: '/sounds/808MA_Orig.wav',
  },
  {
    keyCode: 81,
    code: 'KeyQ',
    keyTrigger: 'Q',
    id: 'CY',
    url: '/sounds/808CY_6_Orig.wav',
  },
  {
    keyCode: 87,
    code: 'KeyW',
    keyTrigger: 'W',
    id: 'OH',
    url: '/sounds/808OHH2_Orig.wav',
  },
  {
    keyCode: 69,
    code: 'KeyE',
    keyTrigger: 'E',
    id: 'CH',
    url: '/sounds/808HH_Orig.wav',
  },
  {
    keyCode: 82,
    code: 'KeyR',
    keyTrigger: 'R',
    id: 'LC',
    url: '/sounds/808LC1_Orig.wav',
  },
  {
    keyCode: 65,
    code: 'KeyA',
    keyTrigger: 'A',
    id: 'HT',
    url: '/sounds/808HT3_Orig.wav',
  },
  {
    keyCode: 83,
    code: 'KeyS',
    keyTrigger: 'S',
    id: 'RS',
    url: '/sounds/808RS_Orig.wav',
  },
  {
    keyCode: 68,
    code: 'KeyD',
    keyTrigger: 'D',
    id: 'CP',
    url: '/sounds/808CP_Orig.wav',
  },
  {
    keyCode: 70,
    code: 'KeyF',
    keyTrigger: 'F',
    id: 'CB',
    url: '/sounds/808CB_Orig.wav',
  },
  {
    keyCode: 90,
    code: 'KeyZ',
    keyTrigger: 'Z',
    id: 'BD',
    url: '/sounds/808BD_T9D5_Orig.wav',
  },
  {
    keyCode: 88,
    code: 'KeyX',
    keyTrigger: 'X',
    id: 'SD',
    url: '/sounds/808SD_3D_Orig.wav',
  },
  {
    keyCode: 67,
    code: 'KeyC',
    keyTrigger: 'C',
    id: 'LT',
    url: '/sounds/808LT3_Orig.wav',
  },
  {
    keyCode: 86,
    code: 'KeyV',
    keyTrigger: 'V',
    id: 'MT',
    url: '/sounds/808MT3_Orig.wav',
  },
]
